[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-python"
