[build]
  command = "npm --prefix frontend ci && npm --prefix frontend run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/process/api/:splat"
  status = 200
